### ISSUE TITLE
setSkinByName not updating skin.

### ISSUE THREAD

**Issue by royletron** [orange-games/phaser-spine#1]
Hey dudes. Firstly, thanks for the plugin. Super awesome and massively useful for our work. 

I am trying to update skins on the fly using setSkinByName(), which works fine on create, but won't work during update - or at least the visible skin isn't changing.

Is this expected? Am I missing something simple?

**Comment by AleBles** [comment]
Hey dude :D,

thanks for using the library, and no that is not expected behaviour. I've updated the [example](https://github.com/orange-games/phaser-spine/blob/master/example/index.html) to changes the skin during update, which seems to work fine there. So without an reproducable example it's kinda hard to figure out what the issue could be.

Pherhaps you could make a [gist](https://gist.github.com/) where the issue is reproducable?

**Comment by royletron** [comment]
Hey @AleBles thanks for the quick update. I think it might actually be down to my spine file... I have [read here](http://esotericsoftware.com/forum/Problem-with-SetSkin-to-change-skin-at-runtime-Unity-5666)

Is there any chance you can provide me the spine file for Buddy so I can have a quick look at how he is setup? Or just a screenie of the tree would suffice!

**Comment by AleBles** [comment]
Sure: https://github.com/orange-games/phaser-spine/commit/9205ec3466b21efd1fa4b3fc99225ebb77a0ffac

**Comment by royletron** [comment]
Hey @AleBles - That was really helpful in showing me that I have a problem with my Spine file, but sadly I have zero idea why it is happening... Is there some magic I am missing?

I have [created a fork](https://github.com/royletron/phaser-spine) and added my stripped down Spine file, and updated the example.html...

I mega appreciate your help, this is driving me insane.

**Comment by AleBles** [comment]
I had a look at your project, but unfortunately I don't really have any Spine runtime experience to point out any errors regarding this. :(

I usually only work with exported data delivered to my by our artists

**Comment by royletron** [comment]
Hey @AleBles,

Sorry to not get back for so long, but I had to move onto other problems. This was ended up being down to me needing to add 'skin change' keyframes on my animations. Essentially a skin change will only kick in when the playhead hits one of these keyframes, so you can manage how the skin change happens (I guess).

Anyway, I have resolved it by adding a lot of these keyframes to my animations, if anyone has a better suggestion I would love to hear it but I guess we can close this for now!

Regards, and thanks for your helps!

Darren

**Comment by AleBles** [comment]
Hey, no problem. 

Good to hear you managed to solve your issue! And thanks for sharing your current solution =)
