### ISSUE TITLE
If you do game.load.spine outside of preload, textAtlas not generated

### ISSUE THREAD

**Issue by shibekin69** [orange-games/phaser-spine#12]
Hi,

I noticed that if I do something like:

this.game.load.spine('spineboy', 'asset/spineboy.json');

...outside Phaser's preload function, it doesn't generate a spineBoyAtlas object in the text cache.

**Comment by AleBles** [comment]
This reply is way overdue but Phaser's preloader does not start working outside preload() unless load.star() is called.

Have you tried that @shibekin69 ?

**Comment by shibekin69** [comment]
I think this might not be an issue anymore. I got stuff to work,
