### ISSUE TITLE
setToSetupPose Not Working?

### ISSUE THREAD

**Issue by shibekin69** [orange-games/phaser-spine#13]
Yeah I think this is broken. If I do a .setToSetupPose to see what it is, it returns a function, but trying to run it doesn't return my spine animation back to the setup pose. Is there a work around for this?

**Comment by AleBles** [comment]
setToSetupPose is heavily used in any of the given examples, would it be possible for you to making a minimum working example with those?

**Comment by shibekin69** [comment]
Let me get back to you on this one ;)

**Comment by shibekin69** [comment]
[testphaserspine.zip](https://github.com/orange-games/phaser-spine/files/442717/testphaserspine.zip)

Here you go. Barebones test of phaser spine and spineboy with the files Phaser.js and Phaser-Spine.js files I'm using. Minimum example of it not working.

**Comment by shibekin69** [comment]
@AleBles, ok, I think I get what the function is for - it's just to refresh the skins and such right, and not to actually to stop the animation and put the character back into the setup pose?
