### ISSUE TITLE
Support for shearing?

### ISSUE THREAD

**Issue by Skeptron** [orange-games/phaser-spine#15]
http://fr.esotericsoftware.com/blog#Shearing

Hi guys!

First, I wanted to tell you guys how freaking awesome this plugin is! Spine is just amazing, it's gonna save us megas of spritesheets data, for much better animations.. And for almost no performance cost!

This plugin rocks.

That said, do you guys plan on adding any new feature, like shearing? Is there any way of "warping" shapes (like distortion?). This helps giving a lot more natural organic feel to the characters.

Thanks a lot!

**Comment by shibekin69** [comment]
I think he might add it when he updates the spine-js code to spine-ts

**Comment by AleBles** [comment]
That's the idea :)

**Comment by Skeptron** [comment]
Great! Do you have any date in mind? (I mean, not the exact day, but a roughly estimated date?)

**Comment by AleBles** [comment]
Honestly, for the moment: this year.

**Comment by AleBles** [comment]
So appearantly I'm a year late!
