### ISSUE TITLE
[SOLVED] Distorted / misplaced slot attachments with .json export Spine version 3.3

### ISSUE THREAD

**Issue by ldacruz** [orange-games/phaser-spine#19]
Hi, 

thanks you for your plugin.

I tested it with a Spine 2.x project and Phaser and everything worked fine. 
Unfortunately we "merged" all of our animations to Spine 3.3
and now the skeleton character attachments (maybe even the bones) are displaced / distorted / shown with an offset: 
![spine3-3_dislocated_slotimages](https://cloud.githubusercontent.com/assets/858433/18254040/08c88a18-739a-11e6-837c-b0a956b6a833.jpg)

Red rectangles are the imported spine character attachments
and in the green rectangle is the correct placed character, as it should be. 

Skeleton character animation is called as written in your documentation with:

> elephant.setAnimationByName(0, "idle", true);

Any idea, why this is happening?

Nobody else seem to have this problem. 
It is a single sprite sheet atlas.
Strange to me, as it was working before and we are not using shear animations or other "fancy" stuff.

Thanks, 
Linda

**Comment by shibekin69** [comment]
Do you by any chance have multi-page texture on when exporting? (texture images is split into multiple files).

EDIT: Ah nevermind. You said single sprite sheet atlas. Can you double check anyway?

I noticed that when Spine editor needs to re-map the images in the texture files, you'll need to force reload the images in the browser as well. In your browser, you can go to the URL of the images and force reload it there. Alternatively,  you can edit the phaser-spine.js file, look for the line where the PNGs are loaded and change it:

from

_this.image(file, cacheData.basePath + '/' + file.substr(0, file.lastIndexOf('.')) + variant + '.png');

to

_this.image(file, cacheData.basePath + '/' + file.substr(0, file.lastIndexOf('.')) + variant + '.png' + '?' + Date.now());

This will append a changing parameter that will force the browser to force reload the file for you.

**Comment by AleBles** [comment]
[shameless plug]
@shibekin69 you can also use my other plugin [phaser-cachebuster](https://github.com/orange-games/phaser-cachebuster) to control cache busting of assets :P
[/shameless plug]

@ldacruz I've seen similar behaviour when the image it self was scaled (I introduced the scaling variants for this), did spine scale down the exported image? If so, that needs to be configured as per https://github.com/orange-games/phaser-spine#scaled-atlases

**Comment by shibekin69** [comment]
Ah I better take a look at that!

Yeah it could be exporting it as a scaled-down texture. Happened to me while playing around with the exporter too.

**Comment by ldacruz** [comment]
Hey, 

thanks for your comments @AleBles and @shibekin69.

The problem was the **scaled atlas**, as I exported with 0.5. 
So this was an easy fix, modifying the atlas name.

Now the remaining problem is the missing trunk. 
I assume this is due to the usage of **mesh deform**?

Does somebody else use mesh deform?

Thanks, 
Linda

![bildschirmfoto 2016-09-12 um 11 42 29](https://cloud.githubusercontent.com/assets/858433/18431753/b3eeb518-78de-11e6-9117-a5816cd0c918.jpg)

**Comment by ldacruz** [comment]
Yes, Mesh Deform seemed to be the issue. 
I've removed mesh deform on the trunk pieces now and it works. 

Thanks for your help! 

![bildschirmfoto 2016-09-12 um 13 01 28](https://cloud.githubusercontent.com/assets/858433/18433643/22feae4a-78e9-11e6-881d-121f569a5e25.jpg)
