### ISSUE TITLE
Combining skins

### ISSUE THREAD

**Issue by chalitnc** [orange-games/phaser-spine#2]
I'm looking to programatically combine skins based on the following post 
[http://esotericsoftware.com/forum/mix-and-match-skin-attachments-618?start=25](http://esotericsoftware.com/forum/mix-and-match-skin-attachments-618?start=25)

Is there a Phaser equivalent for creating a new skin like so :
local combinedSkin = Skin.new("Combined_skin_name")

**Comment by AleBles** [comment]
Not yet, but it seems easy enough to make possible
