### ISSUE TITLE
How to use events?

### ISSUE THREAD

**Issue by shibekin69** [orange-games/phaser-spine#20]
Hi AleBles,

How do you listen for events from spine objects?

**Comment by AleBles** [comment]
There is currently no code that handles events created in the Spine GUI, but it should be fairly easy to add

**Comment by sebas86** [comment]
@shibekin69, please look at this small change https://github.com/orange-games/phaser-spine/pull/39. You can also utilize track returned by Spine.setAnimationByName and Spine.addAnimationByName – both methods return spine.TrackEntry and this object has onEvent member which is function reference – just set your callback.

**Comment by shibekin69** [comment]
Ah! Thanks for the heads up on this one @sebas86 :)

**Comment by AleBles** [comment]
And that got merged, closing this now. Feel free to re-open if anything is wrong/missing
