### ISSUE TITLE
[SOLVED]there maybe a bug about setAnimationByName()

### ISSUE THREAD

**Issue by zk-luke** [orange-games/phaser-spine#23]
I have 5 animations made with spine 3.x .  when i use `setAniamtion()` to change animation ,it doesnt work.
if i invoke `setMixByName(a,b)` and a and b can change,but others still cannot change.

hope to replay. thks man.

please watch the demo [here](https://koalaylj.github.io/index.html) ,click to change animaitons.

repo is [here](https://github.com/koalaylj/koalaylj.github.io)

post:
I am not sure , there minght be some different about spine2.x and 3.x at `animations` section in json files.

**Comment by AleBles** [comment]
You need to call setToSetupPose after switching the animation

``` javascript
            game.input.onDown.add(function() {
              count++;
              count = count % shit.length;
              symbols.setAnimationByName(0, shit[count], true);
              symbols.setToSetupPose();
              console.log("play", shit[count]);
            });
```

**Comment by zk-luke** [comment]
thanks man, it works fine!
