### ISSUE TITLE
Bounding Box attachment types do not store vertices

### ISSUE THREAD

**Issue by AshMobilePie** [orange-games/phaser-spine#25]
We noticed this when replacing our Spine plugin.

The vertices member of BoundingBoxAttachment is a Float32Array, which is a fixed-length data type. As such, when you push the vertices in during readAttachment(), none of the data actually gets stored.

As a temporary fix, we've hacked the readAttachment() method to look like this:

```
        case spine.AttachmentType.boundingbox:
            var attachment = this.attachmentLoader.newBoundingBoxAttachment(skin, name);
            var vertices = map["vertices"];
            attachment.vertices = new spine.Float32Array(vertices.length);
            for (var i = 0, n = vertices.length; i < n; i++){
                attachment.vertices[i] = vertices[i] * scale;
            }
            return attachment;
```

**Comment by AleBles** [comment]
Sorry for not spotting this earlier, nice find!
