### ISSUE TITLE
Reset state with new animation

### ISSUE THREAD

**Issue by Skeptron** [orange-games/phaser-spine#27]
Hi everyone,

I'm having an issue and I think it's because I'm using the lib poorly. I need your help!

When I play an animation, and interrupt it for another animation, weird things happen. Z-order of sprites is sometimes messed up, or data from previous animation is kept. I haven't found a way to "clear" previous animation and start the new one on a clean slate.

For example, I used the spineboy example, which I slightly modified as is : 

```
   function create() {
        //create the spine object
        spineboy = game.add.spine(200, 400, "spineboy");

        // Add animations
        spineboy.addAnimationByName(0, "walk", true);
        spineboy.addAnimationByName(0, "jump", true);

        // Play walk by default
        spineboy.setAnimationByName(0, "walk", true);

        let anim = 1;
        game.input.onDown.add(function(){
          if(anim === 1){
            spineboy.setAnimationByName(0, "jump", true);
            anim = 2;
          }else{
            spineboy.setAnimationByName(0, "walk", true);
            anim = 1;
          }
        });
    }

```

If you use this code and click once, the spineboy will play the jump indefinitely. And if you click a second time it will go back to the walk animation. But the strange thing is, that it will keep any angle it previously had from the jump animation! For example, if you let the boy crouch (before the jump), and then click again, then he will walk but with the same angle he had while crouching!

How could I properly reset all animation data to the walk animation, not inheriting undesired properties from the jump animation?

Thanks a lot guys!

**Comment by shibekin69** [comment]
Tried the tosetuppose function?

**Comment by Skeptron** [comment]
toSetUpPose does fix the angle, which is a great first step, but it does not fix the Z-order of things. Any other suggestion?

Thanks a lot for the help!

**Comment by Skeptron** [comment]
If that helps, I'd add that the messed Z-order only seems to happen on sprites that can vary from one animation to another (for example, a hand sprite that is either closed or open).

**Comment by shibekin69** [comment]
What I do is at the start of each animation (frame 0), I explicitly set the Z-order of objects that need it, otherwise, it'll just carry over the next animation.

**Comment by Skeptron** [comment]
Nice, and how do you do so?

**Comment by shibekin69** [comment]
While in Spine editor, in Animation Mode, activate one of your animations. Then go to the timeline at the bottom and make sure you're at the very first frame. Then go to your Draw Order tree. Drag and drop the order of the images as needed then when you're done, click on the Orange Key Icon beside the Draw Order folder tree. That should set your desired draw order at the start of the animation.
