### ISSUE TITLE
bug about mesh rendering

### ISSUE THREAD

**Issue by zk-luke** [orange-games/phaser-spine#28]
I have an animaiton made by mesh. but  looks like some traingles can not be rendered.
I tried the animation in pixi-spine ,it works well.

I made the demo here (click to play animation): 
* [pixi-spine-mesh](https://koalaylj.github.io/spine/pixi/mesh.html).
* [phaser-spine-mesh](https://koalaylj.github.io/spine/phaser/mesh.html).  

the repo is [here](https://github.com/koalaylj/koalaylj.github.io)

thanks a lot guys.

**Comment by zk-luke** [comment]
@AleBles  sorry to disturb . do you have any idea about this?

**Comment by AleBles** [comment]
That's.. interesting, I don't have a lot of time these days to go into this. But i'll see if I can get something working soon

**Comment by shibekin69** [comment]
@koalaylj aside from meshes, what other advanced spine features are you using in this demo?

**Comment by zk-luke** [comment]
@shibekin69  I didn't use other advanced feature, just mesh and basic bone animation.

**Comment by shibekin69** [comment]
Ah ok. I was wondering how you did the retracting punching glove since it looked like it was on a curved path. Just manual bone animation?

**Comment by AleBles** [comment]
Yeah, meshes don't work on phaser-spine < 4, the upcomming spine-ts implementation should fix this

**Comment by zk-luke** [comment]
thanks a lot , looking forward to v4.
