### ISSUE TITLE
Phaser CE 2.7.2

### ISSUE THREAD

**Issue by codism** [orange-games/phaser-spine#29]
I tried to update this to use the latest Phaser CE 2.7.2 which allows for rotated sprites and other features, but there's a lot of Pixi functionality has been removed and merged which breaks it unfortunately.

e.g. "PIXI.Rope and PIXI.Strip have been removed, and all functionality merged in to Phaser.Rope, to cut down on the number of internal classes and inheritance going on."

**Comment by Pit-the-Angel** [comment]
I've made a version of this which runs on Phaser 2.7.2 CE, guessing i need permission to create a pull request for it. :)  @AleBles

**Comment by AleBles** [comment]
I'm always open for pull requests, you can just submit it :)

Would be nice if it's against the dev branch

**Comment by shibekin69** [comment]
@Pit-the-Angel Is your version Spine-TS already or a modification of the current phaser-spine plugin?

**Comment by Pit-the-Angel** [comment]
Just using the Spine-JS which was being used before. Want to look at making it work with the newest Spine though as one of my projects requires Mesh to be working, which doesn't seem to in the current version.

**Comment by iangregsondev** [comment]
This would be great to see! I think trying to use the spine-ts project would be a great idea. Would allow use to easily upgrade as new versions come along?
