### ISSUE TITLE
Great initiative

### ISSUE THREAD

**Issue by keysim** [orange-games/phaser-spine#3]
Hi, I'm currently trying to do some games on phaser and I buy Spine for the animations, is your phaser-spine pluggin is up to date ? Do you have some documentations ?

Thank you !

**Comment by keysim** [comment]
I'm trying to apply physics, I don't know how to do it, I can't enable the body on it :/

**Comment by AleBles** [comment]
I try to keep the library up to date with the official Spine runtime. I have a new commit lingering around somewhere, I'll push it tomorrow.
As for the docs, yeah I really need to work on those. :p

Ahh yeah, spine animations don't have an body, and I don't expect them to have any time soon. (Unless someone else feels like doing it), sorry

**Comment by keysim** [comment]
Hi again, thank you for the lib. Sadly we can't do some physics with it... Do you maybe know how to add it without doing too much code ? Like maybe linked it to a image not showed which will have physics on it and then mapping it to the sprite animation positions ? I don't know what to do, I'm so sad I can't use my Spine to do my games... (I notice a "bug" in your lib, when you scale your export with Spine, you actualy don't scale the positions when we load it so it's showing the littles bones images with the x1 positions, it's pretty funny but not working haha)

**Comment by AleBles** [comment]
I'm not sure how to tackle the bodies yet, but I'm thinking about it, as for the scaling issue, can you show me an example of it somewhere? Maybe even using code from the examples directory? I recently added two more examples

**Comment by AleBles** [comment]
So I found out what causes the scaling issue. By default the atlas/export/json don't provide any scaling data, unless you specify it at as a suffix of the atlas. This'll be fixed soon where you can specify how the suffix should be handled. As for the bodies, I created a different issue for that: #4, so we can leave this issue to the scaling.

**Comment by keysim** [comment]
Sorry, I don't have time to help you, I'm a student. I hope you will continue doing your pluggin ! I will keep me informed of what you change and try it ! (If you give me some documentations haha)

**Comment by AleBles** [comment]
I just updated the readme with the new scaling options :)
