### ISSUE TITLE
Phaser Spine and Phaser 2.6.2/2.7.3 Loading Bug

### ISSUE THREAD

**Issue by shibekin69** [orange-games/phaser-spine#40]
Hey guys,

This isn't an issue, but just something I thought I'd let you guys know about. If you're using an older version of Phaser Spine (Still using the Fabrique class name, version available around Oct 30, 2016), and Phaser 2.6.2, there's a loading bug that occurs when you've created a save game system and you keep loading a save game that has commands that reloads the stage and add spine objects.

The error is quite random, but the more spine objects you load in, the higher the chances of this happening. It'll throw out a type error about the Canvas2D renderer unable to load a graphic or something because it's not an image.

I'm testing out the latest Phaser Spine with Phaser CE 2.7.3 and so far no problems!

**EDIT: Ok, seems like the problem's still around.**

See attached to see messages when Phaser is set to Canvas and WebGL modes:

![image](https://cloud.githubusercontent.com/assets/12507139/24090860/ce4c7f14-0d7e-11e7-8e22-59ab142aa846.png)

![image](https://cloud.githubusercontent.com/assets/12507139/24090922/6ddfae20-0d7f-11e7-9e64-dec5c92395f7.png)

Here's some things I've figured out so far:

It seems to occur when I've a save game down the line of my scripts. The game relies on custom script files being parsed line-by-line. Loading a game with a marker in the middle of the script with a couple of these spine characters being loaded and faded in seems to trigger the problem.

**Comment by AleBles** [comment]
Would it be possible for you to make a minimal reproducible case? It really sounds like an edge case, and it might also fail on the latest version depending on the cause.

**Comment by shibekin69** [comment]
ok, I think I've found the problem. I think that it triggers when I try to use spine on the images (like fading them in, showing them in the stage) while the spine objects haven't totally loaded yet. Because I'm using a fast forwarding mechanism when loading a save game, I noticed this only happens when doing this. It disappeared when I forced a wait time after putting the spine objects on stage to give it enough time to load up its resources.

**Comment by shibekin69** [comment]
Ok, I think this is it. I have to slow down my fast forwarding mechanism a bit.

**Comment by shibekin69** [comment]
Ok, the bug is quite elusive, but I think I've managed to track it down. What I do with my project is, I have a game.js file that I keep on recycling (restarting), and stuff is preloaded depending on what I've instructed in my JSON files. The instructions on what to load in the JSON file changes depending on the scene/level.

Here's what I've noticed. I usually don't encounter this problem in localhost, because everything's loaded quickly. Makes sense right? It appears only when you upload your game online, where latency, slow and unreliable Internet connectivity become factors. This can be simulated by using Chrome's Throttling. The problem usually occurs when I load a different save game after another, which has different asset loading instructions in the JSON file. 

So the error is usually something along the lines of Phaser.getCache not being able to find an atlas key or an image key. Then when I've an instruction to show the spine object, it'll say it can't draw it in the canvas because it's not an image type of object.

So what I've found out is that after the Preload: {} is done, even if Phaser moves into the next section, like Update: {}, the system is not actually done with the spine objects that I've instructed to have loaded. I've modified phaser-spine to use Phaser's game.load.xxx() features so we can use game.load.onLoadComplete() to wait for the spine objects to fully load up before moving on:

    //Comments - original code. Starts at line 2910
    ...
    //_this.image(file, cacheData.basePath + '/' + file.substr(0, file.lastIndexOf('.')) + variant + '.png');
    _this.game.load.image(file, cacheData.basePath + '/' + file.substr(0, file.lastIndexOf('.')) + variant + '.png');
    ...
    //_this.text(atlasKey, url.substr(0, url.lastIndexOf('.')) + variant + '.atlas');
    _this.game.load.text(atlasKey, url.substr(0, url.lastIndexOf('.')) + variant + '.atlas');
    ...
    //this.json(key, url);
    this.game.load.json(key, url);
    this.game.cache.addSpine(key, cacheData);
    ...

Maybe for smaller spine objects, this won't be necessary. But since I'm loading up several big spine animations (1500 x 1500px), there's a pause of a couple of seconds when loading or reloading them up, which I need in my case or else my game script will encounter problems.

**Comment by AleBles** [comment]
That's really intereseting that that fix would work, because I'm adding the loading methods to Phaser.Loader's prototype, so this.game.load.text should equal this.text.

You already said you're still on the Fabrique version, but do you have an exact version number for me?

**Comment by shibekin69** [comment]
Ah no no, not Fabrique anymore. Just maybe 1 version down from the current one? I'm not an expert at Phaser's stuff, so I don't know if this.text is the same as game.load.text, so I just did it anyway to make sure.

**Comment by shibekin69** [comment]
Says here, phaser-spine version 3.0.1
