### ISSUE TITLE
How can I use callback function when Animation Play Complete?

### ISSUE THREAD

**Issue by SangLiang** [orange-games/phaser-spine#43]
How can I use callback function when Animation Play Complete?

**Comment by SangLiang** [comment]
I have resolved this problem

**Comment by TinyDobbins** [comment]
can you write how your resolve this problem?

**Comment by AleBles** [comment]
I'd say the common accepted awnser would be to implement events in your spine animation because this library (and spine) by default doesn't fire animation complete events.

You can read up on events here: http://esotericsoftware.com/spine-events

**Comment by AleBles** [comment]
Is what I said, but I just found out I've got a pull request open for this xD

**Comment by TinyDobbins** [comment]
@AleBles when you will add this request?

**Comment by AleBles** [comment]
I just did :)
