### ISSUE TITLE
How do I unload spine objects?

### ISSUE THREAD

**Issue by shibekin69** [orange-games/phaser-spine#44]
How do I go about unloading spine objects from the stage without removing the cached textures?

**Comment by AleBles** [comment]
If you mean removing the spine object itself, with all spine references except textures than there is no nice destroy method yet that can do this

If you only want the object removed from the visible stage you could do:
`spine.parent.removeChild(spine);`

**Comment by shibekin69** [comment]
Hmm.. Just as I thought.

Related to that odd loading bug I encountered, here's the weird thing about it - first boot, first load up, even with the speeded up loading of the scene, there's no chance that I'll encounter that bug. It really only appears on the 2nd and succeeding loading of save games. And here I assumed that since all the spine textures have been loaded, there shouldn't be problems anymore.
