### ISSUE TITLE
Upgrade version of spine

### ISSUE THREAD

**Issue by xoorath** [orange-games/phaser-spine#47]
Support for the latest version of spine would really help my team out. If there's any low hanging fruit you're aware of, please let us know. With some direction we might be able to take on some of what's needed to support the latest spine.

The first issue we noticed was no support for the attachment type: path. The error messages generated from trying to load this unsupported attachment type could also be a bit better.

Let me know how I can help!

Thanks

**Comment by shibekin69** [comment]
I think right now, he's having trouble getting Spine-TS to work with Phaser's WebGL mode.

**Comment by AleBles** [comment]
Yeah, it's a combination of me having little to no knowledge of WebGL and having no time to investigate.

Help is always appreciated, I have special branch setup where development is done (https://github.com/orange-games/phaser-spine/tree/spine-ts). And the gist of it is beeing picked up in #11 

So I'm closing this as a duplicate if you don't mind :)
