### ISSUE TITLE
Scale the timeline of an animation

### ISSUE THREAD

**Issue by NeoHoffa** [orange-games/phaser-spine#57]
Is there a way to adjust the speed of an entire animation? For example, if I wanted an animation to animate at half speed, or double speed.

Something to the effect of, mySpine.currentAnimation.timeScale = .5;

Thanks!

**Comment by DavidZwit** [comment]
@NeoHoffa 
You're probably looking for mySpine.state.timeScale :)

**Comment by NeoHoffa** [comment]
@DavidZwit, 

You sir, are a gentleman and a scholar! ;)

Perfect! Thanks!
