### ISSUE TITLE
Issue with flipping images?

### ISSUE THREAD

**Issue by JasonPKaplan** [orange-games/phaser-spine#6]
![atami_spine_correct](https://cloud.githubusercontent.com/assets/3027203/16311921/71c0d7f8-3940-11e6-9fbe-83eccc4e77e8.png)
![atami_spine_default](https://cloud.githubusercontent.com/assets/3027203/16311922/71c83228-3940-11e6-9c04-370a3dd14783.png)
![atami_spine_issue](https://cloud.githubusercontent.com/assets/3027203/16311923/71c8afdc-3940-11e6-9ade-ea4099cb8d1d.png)

Hi there! First off, thanks for putting this together, it's a huge help.

We're experiencing an issue though, as displayed by the images. One shows the correct behaviour in Unity, one shows the neutral state, and one shows the problem behaviour in Phaser. We're flipping some assets during animations across a single axis, but in Phaser it appears to be flipping it along both axis. In this pose, the hand is flipped away from the character, but this results in the hand asset being turned upside down as well.

Any insight would be a tremendous help. We're also seeing an issue with issues of transparency not blending. Is there a way to change the blend mode to additive? PIXI has a blendMode that can be changed but it doesn't appear to be working when applied to my Spine object in Phaser.

Thanks,
JPK

**Comment by AleBles** [comment]
I've actualy encountered this issue myself, but made a fix for it some time ago: https://github.com/orange-games/phaser-spine/commit/89588e85e3e805b9ff001d0a77cc60c8f4e4074a

May I ask on which version you are running?

As for the blendMode, Ill be adding a seperate issue for this, and pick it up whenever I got the time for it.

**Comment by JasonPKaplan** [comment]
Hi Ale,

I'm using the latest build, from 8 days ago.

**Comment by AleBles** [comment]
Okay, I'd love to help you out, but I find it hard doing so without any example (there's lot's of data in spine's JSON file.

Would you mind sending me one so I can see what's wrong?

**Comment by JasonPKaplan** [comment]
[og-spine-phaser.zip](https://github.com/orange-games/phaser-spine/files/334868/og-spine-phaser.zip)

Of course, here's an example project. :) Thanks so much!

Ah, I guess I should note that I did modify the plugin to not throw an exception on bone shear, as my asset was built in Spine 3.3. I've done this in Unity's plugin as well and didn't experience the flipping issue, though.

**Comment by AleBles** [comment]
@JasonPKaplan Could you get the latest build from the repo and check if the committed fix works as expected?

**Comment by JasonPKaplan** [comment]
Flipping issue is resolved, thanks!
