### ISSUE TITLE
any plan for compatibility with Spine version 3.6+ ?

### ISSUE THREAD

**Issue by TinyDobbins** [orange-games/phaser-spine#66]
Let me know please if you have a plan to update this plugin for compatibility with Spine version 3.6+.

**Comment by AleBles** [comment]
I'd love to add that, already started a bit on the spine-ts branch but the issue I'm currently phasing is that I have neither the time (to much focus going to different projects) nor knowledge (canvas implementation works a tad, maybe needs fixes, but I'm not into WebGL) to further the spine-ts implementation

**Comment by shibekin69** [comment]
Should we start putting out a bounty for this?

**Comment by shibekin69** [comment]
I wonder if we can ask @ivanpopelyshev for help...

**Comment by ivanpopelyshev** [comment]
I can just downgrade my stuff that way it works with pixi-v2-ish-phaser.

Also hook it into phaser update cycle.

**Comment by ivanpopelyshev** [comment]
I can try, if you help me to setup me playground and test it. I used phaser 2 or 3 years ago. Is there any big phaser slack/telegram chat i can join to do that in realtime?

**Comment by AleBles** [comment]
That would be awesome!

https://phaser.io/community/slack

I'm also there on slack =)

**Comment by shibekin69** [comment]
@ivanpopelyshev Thanks a lot bro! :)

**Comment by shibekin69** [comment]
BTW, watch out for this bug (Phaser 2.x, current phaser-spine) if it's present:

https://github.com/photonstorm/phaser-ce/issues/149
