### ISSUE TITLE
[Spine-TS] Cannot control alpha

### ISSUE THREAD

**Issue by shibekin69** [orange-games/phaser-spine#73]
I can't control the alpha from either the parent group of the spine object, or the spine object itself. It seems to be ignored.

So these don't work:

spineObj.alpha = 0.6
spineGroup.alpha = 0.6
spineGroup.children[0] = 0.6    //Where spine object is child of spineGroup

If I set:

spineGroup.alpha = 0;

It works by hiding the spine object, but there's no in-between, it's just either visible or not visible. I use tweens to hide and show my spine objects (and the hiding part does free up resources at least). Not sure why this is a problem here...

**Comment by shibekin69** [comment]
Just an observation: If I try adjusting game.world.alpha, it manages to affect the alpha of spine object (on top of everything else.)

**Comment by AleBles** [comment]
Should work now, please try it out =)

**Comment by shibekin69** [comment]
@AleBles 

Ok! Tried it out. I've a group that's holding the spine object. Here are the different commands I've tried out:

aGroup.alpha = 0.5 [DOESN'T WORK, ONLY AFFECTS OTHER NON SPINE OBJECTS]
aGroup.children[0].alpha = 0.5 [WORKS]

**Comment by AleBles** [comment]
How about now?

**Comment by shibekin69** [comment]
I'll give this and the rotation a try later. Will let you know.

**Comment by shibekin69** [comment]
This seems to work.
