### ISSUE TITLE
how to change the tint of spine object?

### ISSUE THREAD

**Issue by TinyDobbins** [orange-games/phaser-spine#81]
does anyone know how to change the tint color of spine object?

 I tried also change the each slot manually:
`hero.skeleton.findSlot('head').currentSprite.tint = 0xFF0000`

nothing happens :(

**Comment by shibekin69** [comment]
Try the property color.r, color.g, color.b.

**Comment by TinyDobbins** [comment]
@shibekin69 I can't find this property in spine object. 

`spine.setTint()` also don't work.

**Comment by shibekin69** [comment]
Maybe it's in the bone?

**Comment by shibekin69** [comment]
Ok, scratch that. Try adjusting these:


    spineObj.skeleton.findSlot('head').r = 1   // red, 0 to 1
    spineObj.skeleton.findSlot('head').g = 1  // green, 0 to 1
    spineObj.skeleton.findSlot('head').b = 1  // blue, 0 to 1
    spineObj.skeleton.findSlot('head').a = 1  // alpha, 0 to 1

I think you set it with a hex value like 0x000000 to 0x0000ff. I'm not sure.

**Comment by TinyDobbins** [comment]
fixed #82 
just need to add `if(slot.currentSprite) `
