### ISSUE TITLE
Disabling inherit scale doesn't work

### ISSUE THREAD

**Issue by lukz** [orange-games/phaser-spine#83]
If child bone scale inheritance is disabled it's scaled anyway.

Case is breathing animation where torso is scaled but child bones not.

To make sure I checked it with skeleton viewer and it's working properly there.

**Comment by shibekin69** [comment]
This works for me using the master branch. What spine editor version are you using to export?

**Comment by lukz** [comment]
Got it! I was using Spine 3.6 and now I read that 3.2 is the one that is supported. Sorry!

**Comment by shibekin69** [comment]
Oh!
