### ISSUE TITLE
Display issues when parameter triangleRendering is false

### ISSUE THREAD

**Issue by marcusIB** [orange-games/phaser-spine#84]
Hi, I having trouble viewing my spine animations when I change triangleRendering to false. 

`this.game.plugins.add(PhaserSpine.SpinePlugin, {
                    debugRendering: false,
                    triangleRendering: false
                });`

Otherwise, when this parameter has true value all works (with triangles of course).

`this.game.plugins.add(PhaserSpine.SpinePlugin, {
                    debugRendering: false,
                    triangleRendering: true
                });`

I'm using 4.0.0-alpha1 version of this api.

Thanks for your attention!

**Comment by marcusIB** [comment]
Well, I solved this issue using webGL instead canvas.

**Comment by AleBles** [comment]
Yeah, spine Canvas doesn't support Meshes, except when triangleRendering is set to true, it uses a special/different/experimental way of rendering the Meshes. Those are expected to not work with triangleRendering disabled on canvas

**Comment by asifmansoor** [comment]
hi, I am looking for the 4.0.0-alpha1 version but unable to find it. Can you guide me on this?
