### ISSUE TITLE
Pause spine object?

### ISSUE THREAD

**Issue by TinyDobbins** [orange-games/phaser-spine#85]
Phaser pause `game.paused = true;`  does not apply to spine objects animation. Add please the opportunity to pause spine animation object.

**Comment by NeoHoffa** [comment]
@AnubisCode 

You can use the following to pause.

`character.state.timeScale = 0; // set to 1 to resume`

**Comment by TinyDobbins** [comment]
@NeoHoffa thanks a lot!

**Comment by AleBles** [comment]
or spine.globalAutoUpdate = false;
