### ISSUE TITLE
Playing multiple animations together

### ISSUE THREAD

**Issue by abhivaidya** [orange-games/phaser-spine#87]
Just wondering how to play multiple animations together. So if my character is talking and walking at the same time or thinking and walking or not talking while walking. Any help there?

**Comment by AleBles** [comment]
Any time you play an animation, you set it to a certain track, by setting run to track 0 and jump to track 1 you should be able to achieve what you want

**Comment by abhivaidya** [comment]
Works beautifully as said. Thanks much
