### ISSUE TITLE
Typescript not working.

### ISSUE THREAD

**Issue by qcdong2016** [orange-games/phaser-spine#9]
![image](https://cloud.githubusercontent.com/assets/6292878/16914779/af1c6cc6-4d26-11e6-91e7-6742b521b40e.png)

**Comment by mungojerry** [comment]
How did you fix this? Am assuming it's a problem at my end but getting very confusing messages back

**Comment by AleBles** [comment]
I'd be happy to help you out, would you mind posting the error's you're getting?

**Comment by qcdong2016** [comment]
![qq 20160725225933](https://cloud.githubusercontent.com/assets/6292878/17105865/8a94694a-52bb-11e6-95e2-8e59d4c6d44b.png)
![qq 20160725225940](https://cloud.githubusercontent.com/assets/6292878/17105859/8986365a-52bb-11e6-9ede-1fae0211b409.png)
![qq 20160725225943](https://cloud.githubusercontent.com/assets/6292878/17105860/89cfd62a-52bb-11e6-989d-f13c3e1e8155.png)

var game: MyGame;
make game as a global and load spine use：
game.loadSpine('goblin', 'res/goblins.json');

**Comment by AleBles** [comment]
Closing this for now, let us know if you hang on anything else
